version: '3.8'

services:
  zookeeper_first:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
  zookeeper_second:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22182:2181"
  zookeeper_third:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22183:2181"
  kafka_first:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_first
    depends_on:
      - zookeeper_first
      - zookeeper_second
      - zookeeper_third
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_first:2181,zookeeper_second:2181,zookeeper_third:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_first:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
    restart: always
  kafka_second:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper_first
      - zookeeper_second
      - zookeeper_third
    ports:
      - "29093:29093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_first:2181,zookeeper_second:2181,zookeeper_third:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_second:9093,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
    restart: always
  kafka_third:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper_first
      - zookeeper_second
      - zookeeper_third
    ports:
      - "29094:29094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_first:2181,zookeeper_second:2181,zookeeper_third:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_third:9094,PLAINTEXT_HOST://localhost:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 3
    restart: always
  localstack:
    image: localstack/localstack
    hostname: localstack
    ports:
      - "4566:4566"
    environment:
      - USE_SSL=false
  kouncil:
    container_name: kouncil
    image: consdata/kouncil:latest
    restart: always
    depends_on:
      - kafka_first
    environment:
      bootstrapServers: kafka_first:9092
    ports:
      - "8090:8080"
  server:
    image: server
    build:
      dockerfile: server/Dockerfile
      context: .
      target: runner
    depends_on:
      - kafka_third
      - localstack
    expose:
      - 8086
    ports:
      - "8086:8086"
    volumes:
      - .:/opt/app
    restart: always
  resizer:
    image: resizer
    build:
      dockerfile: resizer/Dockerfile
      context: .
      target: runner
    depends_on:
      - kafka_third
      - localstack
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always